import React, { ReactNode } from "react";
import Head from "next/head";
import Header from "./Header";

type Props = {
  children: ReactNode;
};

const Layout: React.FC<Props> = (props) => (
  <div className="min-h-screen text-white break-all">
    <Head>
      <title>blogr-demo</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <Header />
    <div>{props.children}</div>
  </div>
);

export default Layout;
